project:
  type: website

website:
  title: "Emrah Kırdök"
  navbar:
    right:
      - about.qmd
      - lectures.qmd
      - talks.qmd
      - icon: github
        href: https://github.com/emrahkirdok
      - icon: twitter
        href: https://twitter.com/emrahkirdok
  reader-mode: true
format:
  html:
    page-layout: article
    theme: vetiver
    css: styles.css
    toc: true
    toc-depth: 2