---
title: "Sallanan Çalıştay: Bir Akademik Toplantı Hikayesi"
author: "Emrah Kırdök, Ph.D."
date: "2023-02-17"
categories: [türkçe, akademi, neomatrix mersin]
lang: tr
draft: true
---

Her şey 2022 yılı Haziran ayında Ankara'da düzenlenen NEOMATRIX buluşmasında başlamıştı:

Emrah Kırdök: Çok güzel bir etkinlik oluyor değil mi?
Anders Götherström: Aynen öyle çok zevkli
Emrah Kırdök: Bunun bir benzerini Mersin'de antik mikroplar üzerine yapmaya ne dersin?
Anders Götherström: Neden olmasın?

Pandemi'nin başından beri Avrupa Birliği tarafından desteklenen NEOMATRIX işbirliği projesi kapsamında çalışmalar gerçekleştiriyoruz. Bu kapsamda, partner ekipler yılın belirli zamanlarında buluşarak, geliştirdikleri yöntemleri ve tecrübelerini paylaşıyorlar. Benim rolüm ise antik metagenomik alanında gerliştirdiğimiz bir yöntem hakkında bir çalıştay hazırlamak oldu.

Çalıştay planları aylar öncesinden başlamıştı aslında. Arkeoloji bölümü tarafından kazılan Uzuncaburç'a bir gezi, akşam ve öğle yemekleri derken bayağı kapsamlı bir organizasyon oldu. Bilimsel içerik da hazırdı, ancak sadece toplamamız gerekiyordu..

Çalıştaydan bir hafta önce İsveç'ten genel doktora öğrencileri Zoe pochon ve Nora Bergfeldt ile birlikte yoğun bir çalışmanaya koyulduk. Üniversite caddesi etrafındaki Blank kahvecisinde oturarak bir hafta içerisine sıfırdan bir çalıştay yazdık. Aşağıdaki fotoğraf bu çalıştayı hazırlarken çekildi.

Sonuç olarak 5 Şubat Pazar akşamı hemen hemen her şey hazırlanmış ve çalıştay'a geçmeye hazırdık. Fotoğraf Pazar akişamı yemekten.

# 6 Pazartesi

Derken 6 Şubat Pazartesi sabahı depremle uyandık. Daha önce kısa sarsıntılar atlatmışım ancak bu gerçekten başkaydı. Yatağım sallanıyor, dolabımın kapılar çarpıyor ve tavandaki lamba sallanıyordu. Bir anda refleks olarak yatağın yanına kıvrıldım ve olabildiğince kapanmaya çalıştım. Ancak yatağımın sol tarafındaki geniş ve camlı balkon kapısı beni endişelendiriyordu. O sırada aklımdan cam kırılırsa olabilecekler geçiyordu. Yatağın diğer tarafında geçmeyi düşünsem de, hareket etmemenin en iyi karar olduğunu hissettim.

Kısa bir süre sonra sarsıntı geçti ve yerimden kalktım. O şokla aklıma ilk gelenler evin yakınında konaklayan Zoe ve Nora oldu.

Daha sonra diğer misafirlerle birlikte otelde kalan Ezgi ile haberleştik, onların da sağlıklı olduğu haberini aldık.

Ancak insanların hepsi sokaklardaydı.

Hala aklımda çalıştay vardı, ertesi gün okul bomboştu. 

Organizasyonun diğer ayağı olan Filiz hanım, ailesinin de göçük altında kaldığını ve ilk günü ertelemenin mantıklı olacağını söylüyordu.

Plan değişikliği için eposta atarak Betül'de buluşmayı teklif ettim. Herkes kabul etti ve orada ne yapacağımzı düşünmeye başladık. Bir çok etkinliğin iptal edilmesi ve durumun izlenmesine karar verdik. Çalıştayın az çok da olsa yürütülmesine olan ilişkin inancım, o sırada bir depremle tamamen bitti. Kendimizi doğrudan dışarıya attık ve güneşli Mersin havasında sahilde yürümeye karar verdik.

Ancak öğleden sonra hasarın boyutu az çok ortaya çıkmaya başlamıştı. İki şehir (Kahramanmaraş ve Hatay) yıkılmış, Mersin'de yaşayan bir çok kişinin (ben dahil) yakınları enkaz altında kalmıştı. Tam bir felaket...

Kötü şartlar ve deprem yüzünden Adana havalimanı iptal, İç Anadolu'da kötü hava şartları sebebiyle de otobüs yolculuğu da bir opsiyon değildi: Mersin'de kalmıştık, ancak havanın güneşli olmasıyla avunuyorduk...

Yurtdışı bağlantımız olan Adana havalimanında uçuşlar iptal olmuş ve yardım ekiplerinin bölgeye ulaşması için ayrılmıştı.



# Salı

Dün kahve içtiğimiz bütün mekanlar artık deprem yüzünden sabaha kadar sığınaklar olmaya başlamıştı insanlar için. 

Akşam ise harika bir olay yaşandı. Hep birlikte depremzedeleri için yardım toplayıp Üniversite'ye bıraktık. Çok teşekkürler

# Çarşamba

Sabah 10 gibi Ankara otobüs yolculuğumuz başladı. Ekibin bir kısmı arababyala giderken, Fransa ve İsveç ekibiyle birlikte ben ve Kıvılcım yollardaydık.

Fotoğraf otobüste çekildi.

Akşam hocaları ODTÜ misafirhanesine yerleştirdik


# Perşembe

Misafirlerimiz ayrıldı. Kuzenimin Ankara'da olabilecği bilgisi üzerine Mustafa ve EEE ile hastaneleri gezmeye başladık. 