on:
  workflow_dispatch:
  push:
    branches: main
name: Quarto Publish
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: false
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Setup packages
        uses: r-lib/actions/setup-r-dependencies@v2
          
          
      #- name: Render Quarto Project
      #  uses: quarto-dev/quarto-actions/render@v2
      #  with:
      #    path: source-folder
      #    to: html
     
      - name: Render to html
        # Add any command line argument needed
        run: |
          quarto render
          
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: "false"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
